require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'Gemfile'  #TODO: Update Gemfile style rules
    - 'db/schema.rb'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Max: 50
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
Metrics/MethodLength:
  Max: 35
Style/PercentLiteralDelimiters:
  Enabled: false
Metrics/AbcSize:
    Max: 35
Rails:
  Enabled: true
Documentation:
  Enabled: false
