require: rubocop-rails
AllCops:
  Exclude:
    - 'Gemfile'  #TODO: Update Gemfile style rules
    - 'db/schema.rb'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
Metrics/MethodLength:
  Max: 35
Style/PercentLiteralDelimiters:
  Enabled: false
Rails:
  Enabled: true
Documentation:
  Enabled: false
