version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
      - redis
    volumes: 
      - gem_cache:/vendor/bundle/ruby/2.5.0/gems
      - web-root:/app
    env_file: .env  
    environment:
      RAILS_ENV: development
    entrypoint: ./script/docker-entrypoint.sh
    networks:
      - app-network

  database:
    image: postgres:11
    environment:
      POSTGRES_USER: $HACKTOBERFEST_DATABASE_USERNAME
      POSTGRES_PASSWORD: $HACKTOBERFEST_DATABASE_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:5.0
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks: 
      - app-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  sidekiq:
    image: hacktoberfest_app
    depends_on:
      - app
    volumes:
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    networks:
      - app-network
    entrypoint: ./script/sidekiq-entrypoint.sh

  webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - app
    volumes: 
      - web-root:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - dhparam:/etc/ssl/certs
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email katy@digitalocean.com --agree-tos --no-eff-email --force-renewal -d hacktoberfest-test.site -d www.hacktoberfest-test.site

volumes:
  db_data:
  gem_cache:
  certbot-etc:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/hacktoberfest/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
  